### ISSUE TITLE
Server specifications

### ISSUE THREAD

**Issue by Devessier** [42Taskmaster/taskmaster#1]
## General specifications

The server will be coded in Go, using the latest version.

The server can not be launched as `root`.

The server must be a daemon.

The server will expose a HTTP REST API.

We will be able to use external libraries only for parsing purposes.

In order to start the server the configuration must be valid. If it's not, the daemon is not launched and the command exits directly and logs an error message.

## Internal specifications

The server will start, kill, keep traces of processes.

Information about processes to launch will be contained in a configuration file. When the server starts we must execute the configuration file. When a `SIGHUP` is received, we must reload the configuration file. All the processes are updated according to the diff: we must not kill all the processes, we must be smart and do only the necessary operations. 

Every event must be logged into a file.

## API specifications

This is a REST API that returns data in JSON.

We expect data to be received as `urlencoded` string, already parsed by `net/http`.

The returned data will have the following structure:

```json
{
    "error": 204,
    "result": {}
}
```

### Endpoints

`GET /status`

Returns the status of all of the programs.

`POST /start`
`POST /stop`
`POST /restart`

Expects a form parameter `programId`. The `programId` is the name of the corresponding program in the configuration file.

`GET /configuration`

Returns the current configuration file.

`PUT /configuration`

Updates the configuration file. The new file is received in the body.

`DELETE /shutdown`

Stops all the programs and exits properly.

## Configuration specifications

```yaml
programs:
    nginx:
        cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
        numprocs: 1
        umask: 022
        workingdir: /tmp
        autostart: true
        autorestart: unexpected
        exitcodes:
            - 0
            - 2
        startretries: 3
        starttime: 5
        stopsignal: TERM
        stoptime: 10
        stdout: /tmp/nginx.stdout
        stderr: /tmp/nginx.stderr
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
```

### Fields

`cmd: string`

Required

Command to launch the program

`numprocs: number`

Default: `1`

Number of processes to launch with this configuration

`umask: string`

Default: inherits server umask

The umask to set to the processes

`workingdir: string`

Default: inherits server workingdir

The directory in which we must launch the processes

`autostart: bool`

Default: `true`

Whether we must start the program when the server is launched.

`autorestart: bool`

Default: `unexpected`

If `false`, server never restarts the processes.

If `true`, server always restarts the processes on exit, without regard to the exit code.

If `unexpected`, server restarts the processes if the exit code is not specified in `exitcodes` list.

`exitcodes: number | list<number>`

Default: `0`

The `exitcodes` are either a list of exit codes **or** a single exit code.

The exit codes are used by `autorestart` parameter if set to `unexpected`.

`starttime: number`

Default: `1`

The maximum time in seconds for the program to start, otherwise it's considered to have failed.

If the value is `0` the program is directly considered to have been launched successfully.

`startretries: number`

Default: `3`

If an attempt to launch a program fails, we increment the current state of startretries and retry to launch the program.
If we reach the `startretries` limit, we exit.
If no error occured, we reset the variable to 0.

`stopsignal: string`

Default: `TERM`

When we must stop a program, we must send `stopsignal` signal to the corresponding processes.

The accepted values are `TERM`, `HUP`, `INT`, `QUIT`, `KILL`, `USR1`, or `USR2`.

`stoptime: number`

Default: `10`

The maximum time for the process to exit with its `stopsignal` before sending a `SIGKILL`.

`stdout: string`

Default: `AUTO`

File location in which redirect `stdout`.

If `AUTO` mode is selected, we redirect to a random file in `/tmp` directory.

If `NONE` mode is selected, we disable `stdout` logging.

`stderr: string`

Default: `AUTO`

File location in which redirect `stderr`.

If `AUTO` mode is selected, we redirect to a random file in `/tmp` directory.

If `NONE` mode is selected, we disable `stderr` logging.

`env: map`

Default: `[]`

Environment to pass to processes
